# Generated by Django 4.0 on 2021-12-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
