# Generated by Django 4.0 on 2021-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_app', '0002_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
