# Generated by Django 4.0 on 2021-12-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_app', '0004_alter_history_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
